version: '3.6'

services:
  api:
    image: quay.io/go-skynet/local-ai:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - HEALTHCHECK_ENDPOINT=http://localhost:8000/readyz
      - REBUILD=false
      - BUILD_TYPE=
      - GALLERIES=[{"name":"model-gallery", "url":"github:go-skynet/model-gallery/index.yaml"}]
      - 'PRELOAD_MODELS=[{"url": "github:go-skynet/model-gallery/bert-embeddings.yaml","name": "text-embedding-ada-002"},{"url": "github:luoweb/model-gallery/baichuan-7b.yaml","name": "gpt-3.5-turbo"},{"url": "github:luoweb/model-gallery/stablediffusion.yaml","name": "stablediffusion"}]'
    env_file:
      - .env
    volumes:
      - ./models:/models:cached
    command: ["/usr/bin/local-ai" ]
