ARG BASE_IMAGE=ubuntu:22.04

FROM ${BASE_IMAGE} 

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai

RUN apt-get update && apt-get install -y pciutils && apt-get clean

COPY aio/ /aio
ENTRYPOINT [ "/aio/entrypoint.sh" ]